package com.notel.notel.util

import android.content.Context
import android.graphics.*
import android.graphics.pdf.PdfDocument
import com.notel.notel.data.local.entity.LogEntry
import com.notel.notel.data.repository.LogRepository
import dagger.hilt.android.qualifiers.ApplicationContext
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*
import android.provider.MediaStore
import android.content.ContentValues
import android.os.Environment
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class ReportGenerator @Inject constructor(
    @ApplicationContext private val context: Context,
    private val logRepository: LogRepository
) {

    /**
     * Generates a professional health report as a PDF.
     * Consolidates logs and asks Gemini for a natural language summary first.
     */
    suspend fun generateReport(allEntries: List<LogEntry>, categories: List<com.notel.notel.data.local.entity.Category>): File? {
        val summaryResult = logRepository.getMedicalReportSummary(categories)
        val summary = summaryResult.getOrDefault("Clinical summary unavailable. Analysis based on raw logs.")
        val catMap = categories.associate { it.id to it.name }

        val pdfDocument = PdfDocument()
        val paint = Paint()
        val titlePaint = Paint().apply {
            color = Color.rgb(33, 33, 33)
            textSize = 24f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        }
        val sectionPaint = Paint().apply {
            color = Color.rgb(0, 102, 204) // Professional Blue
            textSize = 18f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        }
        val bodyPaint = Paint().apply {
            color = Color.rgb(66, 66, 66)
            textSize = 12f
        }
        val boldBodyPaint = Paint().apply {
            color = Color.BLACK
            textSize = 12f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        }
        val linePaint = Paint().apply {
            color = Color.LTGRAY
            strokeWidth = 1f
        }

        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4 size
        var page = pdfDocument.startPage(pageInfo)
        var canvas = page.canvas

        var y = 60f
        val margin = 50f
        val contentWidth = 495f

        canvas.drawText("Jot — Clinical Longitudinal Report", margin, y, titlePaint)
        y += 12f
        canvas.drawLine(margin, y, margin + contentWidth, y, linePaint)
        y += 28f
        
        canvas.drawText("Patient Report Generated: ${SimpleDateFormat("MMM dd, yyyy", Locale.getDefault()).format(Date())}", margin, y, bodyPaint)
        y += 40f

        // Advanced Parsing Logic
        val rawLines = summary.split("\n")
        rawLines.forEach { line ->
            if (y > 780) { // New Page
                pdfDocument.finishPage(page)
                page = pdfDocument.startPage(pageInfo)
                canvas = page.canvas
                y = 60f
            }

            when {
                line.contains("[SECTION]") -> {
                    y += 15f
                    val cleanSection = line.replace("[SECTION]", "").replace("[BOLD]", "").replace("*", "").replace("#", "").trim()
                    canvas.drawText(cleanSection, margin, y, sectionPaint)
                    y += 8f
                    canvas.drawLine(margin, y, margin + 80f, y, sectionPaint.apply { strokeWidth = 2f })
                    y += 25f
                }
                line.contains("[BULLET]") -> {
                    val cleanBullet = line.replace("[BULLET]", "").replace("-", "").replace("*", "").trim()
                    drawFormattedLine("• $cleanBullet", margin + 15f, y, contentWidth - 15f, canvas, bodyPaint, boldBodyPaint).let { 
                        y = it 
                    }
                    y += 8f
                }
                else -> {
                    drawFormattedLine(line, margin, y, contentWidth, canvas, bodyPaint, boldBodyPaint).let { 
                        y = it 
                    }
                    y += 8f
                }
            }
        }

        y += 30f
        if (y < 750) {
            canvas.drawLine(margin, y, margin + contentWidth, y, linePaint)
            y += 25f
            canvas.drawText("Disclaimer: This report is generated by AI based on personal logs and should be reviewed by a medical professional.", margin, y, bodyPaint.apply { textSize = 9f; color = Color.GRAY })
        }

        pdfDocument.finishPage(page)

        val fileName = "Jot_Report_${SimpleDateFormat("MMM_dd_yyyy", Locale.getDefault()).format(Date())}.pdf"
        val cacheFile = File(context.cacheDir, fileName)
        try {
            pdfDocument.writeTo(FileOutputStream(cacheFile))
            saveToDownloads(cacheFile, fileName)
        } catch (e: Exception) {
            e.printStackTrace()
            return null
        } finally {
            pdfDocument.close()
        }

        return cacheFile
    }

    private fun drawFormattedLine(
        text: String, 
        x: Float, 
        currentY: Float, 
        width: Float, 
        canvas: Canvas, 
        paint: Paint, 
        boldPaint: Paint
    ): Float {
        var y = currentY
        val lines = wrapText(text, width, paint)
        var isCurrentlyBold = false // Track bold state across wrapped lines of the same logical entry

        lines.forEach { line ->
            var currentX = x
            // Split by markers but keep them for state tracking
            val parts = line.split("[BOLD]")
            
            parts.forEachIndexed { index, part ->
                // If it's the first part and we were bold from previous line, start bold
                // Subsequent parts toggle based on 'isCurrentlyBold'
                val p = if (isCurrentlyBold) boldPaint else paint
                canvas.drawText(part, currentX, y, p)
                currentX += p.measureText(part)
                
                // Toggle bold state for the NEXT part (unless it's the last part of this line)
                if (index < parts.size - 1) {
                    isCurrentlyBold = !isCurrentlyBold
                }
            }
            y += 18f
        }
        return y
    }

    /**
     * Permanent storage in Downloads folder via MediaStore
     */
    private fun saveToDownloads(file: File, fileName: String) {
        val resolver = context.contentResolver
        val contentValues = android.content.ContentValues().apply {
            put(android.provider.MediaStore.MediaColumns.DISPLAY_NAME, fileName)
            put(android.provider.MediaStore.MediaColumns.MIME_TYPE, "application/pdf")
            put(android.provider.MediaStore.MediaColumns.RELATIVE_PATH, android.os.Environment.DIRECTORY_DOWNLOADS)
        }

        val uri = resolver.insert(android.provider.MediaStore.Downloads.EXTERNAL_CONTENT_URI, contentValues)
        uri?.let {
            resolver.openOutputStream(it)?.use { outputStream ->
                file.inputStream().use { inputStream ->
                    inputStream.copyTo(outputStream)
                }
            }
        }
    }

    private fun wrapText(text: String, width: Float, paint: Paint): List<String> {
        val words = text.split(" ")
        val lines = mutableListOf<String>()
        var currentLine = StringBuilder()

        for (word in words) {
            val testLine = if (currentLine.isEmpty()) word else "${currentLine} $word"
            if (paint.measureText(testLine) <= width) {
                currentLine.append(if (currentLine.isEmpty()) word else " $word")
            } else {
                lines.add(currentLine.toString())
                currentLine = StringBuilder(word)
            }
        }
        if (currentLine.isNotEmpty()) lines.add(currentLine.toString())
        return lines
    }
}
